### ISSUE TITLE
Monitoring and Alerting requirements for existing managed stack

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#357]
This is a tracker issue to capture requirements, changes for Monitoring stack 

## Requirements
- Migrate all alerting and monitoring resources from odh-deployer
- Setup alerts only when a component is in `Managed` state
- Scope changes required to move to new monitoring stack.
- Identify new components and additional alerts required.

## Changes
- [x] https://github.com/red-hat-data-services/rhods-operator/pull/67
   - [x] split monitoring from operator git repo into small chunks for each components
   - [x] move "monitoring + anaconda" from odh-manifests into rhods-operator 
   - [x] add support in dockerfile to include "monitoring" from operator
   - [x] add distributed new monitoring
- [x] change logic of checking platform: https://github.com/opendatahub-io/opendatahub-operator/pull/627
- [x] apply fix from previous test https://github.com/red-hat-data-services/rhods-operator/pull/16 
- [ ] sync logic of monitoring in ODH  https://github.com/opendatahub-io/opendatahub-operator/pull/618
- [ ] cleanup "monitoring + anaconda" in odh-manifests which has been duplicated in operator repo  https://github.com/red-hat-data-services/odh-manifests/pull/478

**Comment by zdtsw** [comment]
ref: https://github.com/opendatahub-io/opendatahub-operator/issues/341

**Comment by zdtsw** [comment]
looks like in prometheus` v2.43.0 `https://github.com/prometheus/prometheus/releases/tag/v2.43.0 the feature has been added to support "scrape_config_files" 
but the "latest" image we can use registry.redhat.io/openshift4/ose-prometheus@sha256:2572eff86dc111203c5de6ce7325cc061ddb4bd737e09a1639313f3a9ed07a9c was built off `2.42.0 `

**Comment by zdtsw** [comment]
after a first test with QE, some parts need to figure:
- when user update notification mail, how this will be reflact to the configmap? need to understand how v1 did this
- blackbox if this need to be split to component-based config? seems it is adding label of components?

**Comment by VaishnaviHire** [comment]
Hi @zdtsw for  - 

>  when user update notification mail, how this will be reflact to the configmap? need to understand how v1 did this

This will be a separate PR that should add the changes to watch the addn-parameters configmap. For v1 operator the change was added here - https://github.com/red-hat-data-services/opendatahub-operator/pull/133

**Comment by VaishnaviHire** [comment]
@zdtsw Can we close this as completed?
