### ISSUE TITLE
Track Efforts to add support for managed platform

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#415]
This is a tracking issue that includes PRs/issues merged in efforts to support the new version of the operator for managed platforms

- [x] https://github.com/opendatahub-io/opendatahub-operator/issues/393
- [x] https://github.com/opendatahub-io/opendatahub-operator/issues/373
- [x] https://github.com/opendatahub-io/opendatahub-operator/pull/375
- [x] https://github.com/opendatahub-io/opendatahub-operator/pull/413
- [x] https://github.com/opendatahub-io/opendatahub-operator/pull/403
- [x] https://github.com/opendatahub-io/opendatahub-operator/pull/402
- [x] https://github.com/opendatahub-io/opendatahub-operator/pull/400
- [x] https://github.com/opendatahub-io/opendatahub-operator/pull/397
- [x] https://github.com/red-hat-data-services/rhods-operator/pull/1

**Comment by VaishnaviHire** [comment]
This is a tracker issue and has been already verified in previous releases
