### ISSUE TITLE
Implement Dev Mode for the Operator APIs

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#440]
The current implementation of the operator is opinionated with regards to manifests, namespaces and other configurations. Add support for configuring remote manifests, user-defined namespaces for `dev` users and testing usecases

- [x] https://github.com/opendatahub-io/opendatahub-operator/issues/372
- [x] https://github.com/opendatahub-io/opendatahub-operator/issues/338
- [ ]  Add Support for Custom Parameters
