### ISSUE TITLE
Add Github Workflows to Automate Build and Test Tasks

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#520]
Create workflows to automate operator build and running of operator tests . 

- [ ] Create workflow that builds operator bundle from the image created in OpenShift CI by [job](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-opendatahub-io-opendatahub-operator-main-opendatahub-operator-pr-image-mirror) 
- [ ] Create workflow to set `Kind` cluster and install operator bundle
- [ ] Create workflow to run e2e tests in the above created cluster.

Ref : DataSciience Pipelines- https://github.com/opendatahub-io/data-science-pipelines-operator/actions

**Comment by AjayJagan** [comment]
Here is the corresponding JIRA for the same: https://issues.redhat.com/browse/RHOAIENG-811. So lets track it here :)
