### ISSUE TITLE
[feature-tracker] Move dashboard CRD away from operator

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/opendatahub-operator#534]
create a tracker for this issue
- [x] https://github.com/opendatahub-io/opendatahub-operator/issues/531 include in ODH 1.10
- [ ] [if any documentation/screenshots need updates for ODH 1.10](https://github.com/opendatahub-io/opendatahub.io/pull/196)
- [ ] sync changes to downstream no early than 1.34
- [ ] [cleanup live-builder v2 once sync downstream done](https://gitlab.cee.redhat.com/data-hub/rhods-live-builder/-/merge_requests/281)
- [ ] [cleanup midstream v2 once sync downstream done](https://gitlab.cee.redhat.com/data-hub/rhods-cpaas-midstream/-/merge_requests/1148)
