### ISSUE TITLE
Moving Operator to all supported release branches.

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#555]
In order for v2 operator to migrate to all supported branches, following tasks need to be completed - 

## Required Issues

- [x] #357
- [x] #461
- [x] #556
- [x] Modelmesh and Kserve compatibility
- [x] Update managed platform bundle
- [x] Documentation/implemntation changes around dependency handling

## Other Issues
- Integration of new components
- Integration with Servicemesh

**Comment by VaishnaviHire** [comment]
Closing this as completed
