### ISSUE TITLE
[tracker]: transition for manifests for downstream components

### ISSUE THREAD

**Issue by zdtsw** [opendatahub-io/opendatahub-operator#579]
list for the components to use component repo to host manifests in **downstream**:
- [x] Downstream specific manifests - **TBD** e.g monitoring, osd-config
- [ ] dashboard @lucferbux: after discussion dashboard will keep using downstream odh-manifests for now.
- [x] dsp
- [x] workbench @harshad16 
   - [x] notebookimage
   - [x] nbc
- [x] kserve @Jooho 
- [x] modelmesh @Jooho 
- [x] DW  @dimakis 
  - [x]  codeflare
  - [x] ray
- [x] trusty @RobGeada / @ruivieira

**Comment by HumairAK** [comment]
DSP is good to go on this front.

**Comment by VaishnaviHire** [comment]
> DSP is good to go on this front. Downstream component manifest location can be used for v2 operator deploys.

Hi @HumairAK , for 1.34, we still would needDSP to update red-hat-data-services/odh-manifests. This is to ensure we have all the components migrated at once.

**Comment by HumairAK** [comment]
@VaishnaviHire yep, odh-manifests is already updated for v1.34, for dsp. We will probably update in v1.35 as well just to be safe.

**Comment by anishasthana** [comment]
I'm feeling confident for distributed workloads. FYI @dimakis

**Comment by andrewballantyne** [comment]
We should be fine from a downstream manifests perspective. We'll make sure to sync again. FWIW, @VaishnaviHire & I did suggest a better RHODS integration model at the Architectural Council yesterday -- I made a follow up in [slack](https://redhat-internal.slack.com/archives/C05KDB2HFQQ/p1697730396577399) as well.

**Comment by harshad16** [comment]
I think we can make it too, confidence level: moderate :sweat_smile: 
Working on it now, will keep you all updated.

**Comment by VaishnaviHire** [comment]
Hi @RobGeada , for trustyai we would need to update the component manifests to include `rhods` overlay

**Comment by israel-hdez** [comment]
Hey!

For downstream, KServe is ready. In KServe repo, the entrypoint you should use is `config/overlays/odh` (i.e., please, don't use `config/default').

For ODH, we are still on it.

**Comment by harshad16** [comment]
Workbench updates:

1. Notebook images:  
Manifests path: [manifests/base](https://github.com/red-hat-data-services/notebooks/tree/main/manifests/base)
Branch: [rhods-1.35](https://github.com/red-hat-data-services/notebooks/tree/rhods-1.35)

It should have all the imagestream set properly.

2. Kubeflow:
Manifests path: [components/base]https://github.com/red-hat-data-services/kubeflow/tree/master/components/base
Branch: [rhods-1.35](https://github.com/red-hat-data-services/kubeflow/tree/rhods-1.35)
Note: This branch would be available, once DevOps creates them on feature-freeze.

**Comment by zdtsw** [comment]
> Hey!
> 
> For downstream, KServe is ready. In KServe repo, the entrypoint you should use is `config/overlays/odh` (i.e., please, don't use `config/default`).
> 
> For ODH, we are still on it.

thanks! need to confirm the branch is "release-v0.11.0" to use ?

**Comment by zdtsw** [comment]
> Workbench updates: We seem to be ready for the in-repo manifests pull.
> 
> 1. Notebook images:
>    Manifests path: [manifests/base](https://github.com/red-hat-data-services/notebooks/tree/main/manifests/base)
>    Branch: [rhods-1.35](https://github.com/red-hat-data-services/notebooks/tree/rhods-1.35)
> 
> It should have all the imagestream set properly.
> 
> 2. Notebook-controller:
>    Manifests path: [components/base](https://github.com/red-hat-data-services/kubeflow/tree/master/components/base)
>    Branch: [rhods-1.35](https://github.com/red-hat-data-services/kubeflow/tree/rhods-1.35)
>    Note: This branch would be available, once DevOps creates them on feature-freeze.

thanks!
2 things: 
- the new branch probably will be named as rhods-2.4 to cut over 1.35
- can we make the same structure for nbc just like in ODH? now in rhods the entrypoint is component/base with both 2 nbc, then we need to change the logic in the operator. Or if you can make two part, set the image in 
  1. components/notebook-controller/config
  2. components/odh-notebook-controller/config 
  then will be easier for us.

**Comment by harshad16** [comment]
@zdtsw thank you for the information.

> thanks! 3 things to check:
> 
> * the new branch probably will be named as rhods-2.4 to cut over 1.35

On the Notebook repo, as per the direction:
we have cut the branch:  https://github.com/red-hat-data-services/notebooks/tree/rhods-2.4

> * can we make the same structure for nbc just like in ODH? now in rhods the entrypoint is component/base with both 2 nbc, then we need to change the logic in the operator. Or if you can make two part, set the image in
>   
>   1. components/notebook-controller/config
>   2. components/odh-notebook-controller/config
>      then will be easier for us.

Sorry i didn't follow this one.
Is this what you meant ? https://github.com/red-hat-data-services/kubeflow/pull/29

> * is Manifests path: [manifests/base](https://github.com/red-hat-data-services/notebooks/tree/main/manifests/base) is correct one to use? or should it be the notebooks/manifests/overlays/addintonal?

To stay in line with what we had in RHODS/odh-manifest for notebook, 
we have kept the in-repo manifests only as: 
https://github.com/red-hat-data-services/notebooks/tree/rhods-2.4/manifests/base
if adding  overlays/additional  helps, let us know we can create that overlays.

**Comment by israel-hdez** [comment]
> > Hey!
> > For downstream, KServe is ready. In KServe repo, the entrypoint you should use is `config/overlays/odh` (i.e., please, don't use `config/default`).
> > For ODH, we are still on it.
> 
> thanks! need to confirm the branch is "release-v0.11.0" to use ?

@zdtsw Yes, that's the branch to  use.
Although, I want to emphasize that this is for RHODS release. For ODH 1.11 release we expect to use a different branch.

**Comment by zdtsw** [comment]
> > > Hey!
> > > For downstream, KServe is ready. In KServe repo, the entrypoint you should use is `config/overlays/odh` (i.e., please, don't use `config/default`).
> > > For ODH, we are still on it.
> > 
> > 
> > thanks! need to confirm the branch is "release-v0.11.0" to use ?
> 
> @zdtsw Yes, that's the branch to use. Although, I want to emphasize that this is for RHODS release. For ODH 1.11 release we expect to use a different branch.
> 
> EDIT: BTW, let me know if you will need a tag.

sorry i am confused. so you want RHODS 2.4 build to use opendatahub-io/kserve release-v0.11.0 branch to get manifests?
i do not think we can cross org to do build.
- ODH can use opendatahub-io/kserve branch, 
- RHODS need to use red-hat-data-services/kserve branch

**Comment by lucferbux** [comment]
@zdtsw We've created https://github.com/red-hat-data-services/odh-dashboard/pull/302 for 2.4, it should include the same tree as the manifest had at that time, so except changing the location, i think the rest should be the same

**Comment by zdtsw** [comment]
> @zdtsw We've created [red-hat-data-services/odh-dashboard#302](https://github.com/red-hat-data-services/odh-dashboard/pull/302) for 2.4, it should include the same tree as the manifest had at that time, so except changing the location, i think the rest should be the same

thanks! i will do a test first

**Comment by Jooho** [comment]
@zdtsw Modelmesh is ready to use component manifests 
- https://github.com/opendatahub-io/modelmesh-serving/pull/237 
- https://github.com/opendatahub-io/modelmesh-serving/pull/241 (RHODS 1.35)
- https://github.com/opendatahub-io/modelmesh-serving/pull/242 (ODH 1.11)

operator PR: https://github.com/opendatahub-io/opendatahub-operator/pull/639

**Comment by zdtsw** [comment]
to wrap it up from offline discussion for `kserve` and `modelmesh` in RHODS: 

- `rhods-2.4` is the branch to build 
- all 3 repo: `kserve`, `odh-model-controller` and `model-mesh `are ready

**Comment by zdtsw** [comment]
close this tracker as we have all components transit to in-repo manifests with dashboard as exception :P
